[package]
name = "riff-api"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Riff's API layer for music providers."

[dependencies]
riff-auth = { path = "../riff-auth" }
riff-config = { path = "../riff-config" }
spotify-api = { path = "../../generated/spotify-api" }

serde_json = "1.0.96"
thiserror = "1.0.40"
async-trait = "0.1"
log = "0.4.17"
httpdate = "1.0.3"
glib = "0.20"
gdk-pixbuf = "^0.20"
futures = "0.3.18"
uuid = { version = "1.18", features = ["v5"] }

[dependencies.serde]
version = "^1.0.136"
features = ["derive"]

[dependencies.gdk]
version = "^0.9"
package = "gdk4"

[dependencies.tokio]
version = "1"
features = ["rt", "fs", "macros", "sync", "time"]

[dependencies.isahc]
version = "^1.7.2"
features = ["json"]

[dependencies.gettext-rs]
version = "=0.7.0"
features = ["gettext-system"]
